CREATE TABLE invitations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sender_id INTEGER NOT NULL,
  receiver_id INTEGER NOT NULL,
  status INTEGER DEFAULT NULL, -- 0 = accepted, 1 = rejected
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  disabled_at INTEGER DEFAULT NULL,
  FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE
);
